module.exports = {
  menuList: [
    {
      title: '八皇后算法',
      path: 'Queen',
      icon: '',
      tags: 'Algorithm',
      description: '八皇后算法，棋盘上的每个皇后当前行、列、以及斜角方向均不能有另外的皇后',
      category: 'algorithm',
    },
    {
      title: '圆环动画',
      path: 'Loading1',
      icon: '',
      tags: 'Animation, Css',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '进度条动画',
      path: 'Loading2',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '加载动画',
      path: 'Loading3',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '加载动画',
      path: 'Loading4',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '加载动画',
      path: 'Loading5',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '加载动画',
      path: 'Loading6',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '加载动画',
      path: 'Loading7',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '加载动画',
      path: 'Loading8',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '加载动画',
      path: 'Loading9',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '加载动画',
      path: 'Loading10',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '加载动画',
      path: 'Loading11',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '加载动画',
      path: 'Loading12',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
  ]
}
