module.exports = {
  menuList: [
    {
      title: 'A*算法',
      path: 'AlgorithmAStar',
      icon: '',
      tags: 'Algorithm',
      description:
        'A*算法，从某点位置出发，以最优路线寻找到目标位置，实现思路是，获取当前位置的上下左右周围的元素位置，根据offset的位置来确定下一个最近的点，循环操作来达到目标点。',
      category: 'algorithm',
    },
    {
      title: '概率-抽奖游戏',
      path: 'AlgorithmLottery',
      icon: '',
      tags: 'Algorithm',
      description: '使用概率实现简单的抽奖程序',
      category: 'algorithm',
    },
    {
      title: '矩阵互换',
      path: 'AlgorithmMatrix',
      icon: '',
      tags: 'Algorithm, Matrix',
      description: '矩阵互换',
      category: 'algorithm',
    },
    {
      title: '八皇后算法',
      path: 'AlgorithmQueen',
      icon: '',
      tags: 'Algorithm',
      description:
        '八皇后算法，棋盘上的每个皇后当前行、列、以及斜角方向均不能有另外的皇后',
      category: 'algorithm',
    },
    {
      title: '动画-圆周运动',
      path: 'Loading1',
      icon: '',
      tags: 'Animation, Css',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '动画-三个圆点跳动',
      path: 'Loading2',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '动画-圆点循环闪烁',
      path: 'Loading3',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '动画-呼吸心跳',
      path: 'Loading4',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '动画-圆点往返回弹',
      path: 'Loading5',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '动画-圆点环形运动',
      path: 'Loading6',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '动画-圆点环形大小运动',
      path: 'Loading7',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '动画-柱形上下运动',
      path: 'Loading8',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '动画-圆点绕圆环圆周运动',
      path: 'Loading9',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '动画-进度条',
      path: 'Loading10',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '动画-圆点往返碰撞变形',
      path: 'Loading11',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '动画-圆点三角变换',
      path: 'Loading12',
      icon: '',
      tags: '',
      description: 'transform, rotate, animation',
      category: 'animate',
    },
    {
      title: '角度',
      path: 'CssAngle',
      icon: '',
      tags: '',
      description: 'linear-gradient, before, translate, transform-origin',
      category: 'css',
    },
    {
      title: '边框',
      path: 'CssBorder',
      icon: '',
      tags: 'border',
      description: 'border',
      category: 'css',
    },
    {
      title: '阴影',
      path: 'CssBoxShadow',
      icon: '',
      tags: 'shadow',
      description: 'shadow',
      category: 'css',
    },
    {
      title: '居中',
      path: 'CssCenter',
      icon: '',
      tags: 'layout, center',
      description: '居中版',
      category: 'css',
    },
    {
      title: '复选框',
      path: 'CssCheckbox',
      icon: '',
      tags: 'from, checkbox',
      description: '自定义 checkbox 复选框',
      category: 'css',
    },
    {
      title: 'Filter',
      path: 'CssFilter',
      icon: '',
      tags: 'filter, blur',
      description: 'filter阴影模糊',
      category: 'css',
    },
    {
      title: '闪电划过效果',
      path: 'CssFlashMove',
      icon: '',
      tags: 'linear-gradient, animation, background-clip',
      description: '使用css的渐变与animation动画运动，实现一闪而过的效果',
      category: 'css',
    },
    {
      title: 'CSS文字特效',
      path: 'CssFont',
      icon: '',
      tags: 'linear-gradient, text-shadow, filter, before',
      description: '使用伪元素与文字阴影，过滤实现文字特效',
      category: 'css',
    },
    {
      title: '渐变',
      path: 'CssGradient',
      icon: '',
      tags: 'linear-gradient, radial-gradient',
      description: '线性渐变、径向渐变',
      category: 'css',
    },
    {
      title: '元素选择',
      path: 'CssNth',
      icon: '',
      tags: 'nth-child, nth-of-type, nth-last-child',
      description: '元素匹配的使用',
      category: 'css',
    },
    {
      title: '元素选择',
      path: 'CssScrollNotice',
      icon: '',
      tags: 'background-attachment',
      description: '自定义滚动效果',
      category: 'css',
    },
    {
      title: '形状',
      path: 'CssSharp',
      icon: '',
      tags: 'background-attachment',
      description: '各种形状',
      category: 'css',
    },
    {
      title: '播放器',
      path: 'DiyPlayer',
      icon: '',
      tags: 'background-attachment',
      description: '自定义视频播放器',
      category: 'js',
    },
    {
      title: '拖拽',
      path: 'Drag',
      icon: '',
      tags: 'onmousedown, onmousemove, onmouseup',
      description: '可拖动的带重力效果',
      category: 'js',
    },
    {
      title: '拖拽购物车',
      path: 'DragCart',
      icon: '',
      tags: 'onmousedown, onmousemove, onmouseup',
      description: '可直接将商品拖至购物车，并自动计算价格结果',
      category: 'js',
    },
    {
      title: '拖拽上传图片',
      path: 'DragUpload',
      icon: '',
      tags: 'onmousedown, onmousemove, onmouseup',
      description: '将图片拖至指定位置，实现上传图片效果',
      category: 'js',
    },
    {
      title: 'Hover',
      path: 'Hover',
      icon: '',
      tags: 'onmousedown, onmouseenter, onmouseleave',
      description: '按钮hover效果',
      category: 'js',
    },
    {
      title: '无缝滚动',
      path: 'MoveLoop',
      icon: '',
      tags: 'transiton, animation, animation-play-state',
      description:
        '无缝滚动，使用animation-play-state 属性，在鼠标移至元素内后暂停滚动',
      category: 'js',
    },
    {
      title: '幻灯片',
      path: 'Slider1',
      icon: '',
      tags: '',
      description:
        '鼠标移入幻灯片对应下标的圆点切换内容',
      category: 'js',
    },
    {
      title: '幻灯片-可拖拽切换',
      path: 'Slider2',
      icon: '',
      tags: 'mousedown, mousemove, mouseup, touchstart, touchmove, touchend',
      description:
        '可拖拽切换幻灯片',
      category: 'js',
    },
    {
      title: '幻灯片-切片飘出',
      path: 'Slider4',
      icon: '',
      tags: 'transiton, animation, animation-play-state',
      description:
        '',
      category: 'js',
    },
    {
      title: '幻灯片-3D切块旋转效果',
      path: 'Slider5',
      icon: '',
      tags: 'transiton, animation, animation-play-state',
      description:
        '',
      category: 'js',
    },
    {
      title: '图片旋转',
      path: 'CanvasImageRotate',
      icon: '',
      tags: 'canvas',
      description: '使用Canvas处理图片旋转',
      category: 'js',
    },
    {
      title: '时钟',
      path: 'CanvasClock',
      icon: '',
      tags: 'canvas, clock, Date',
      description: '使用Canvas画时钟',
      category: 'js',
    },
    {
      title: '五子棋',
      path: 'CanvasChess',
      icon: '',
      tags: 'canvas, chess',
      description: 'Canvas 实现五子棋',
      category: 'js',
    },
    {
      title: '布局-多列布局',
      path: 'LayoutColumn',
      icon: '',
      tags: 'felx, table, padding, margin',
      description: '多列布局',
      category: 'layout',
    },
    {
      title: '布局-等高',
      path: 'LayoutAverageHeight',
      icon: '',
      tags: 'felx, table, padding, margin',
      description: '多种方式实现等高均分布局',
      category: 'layout',
    },
    {
      title: '布局-等宽平分',
      path: 'LayoutAverageWidth',
      icon: '',
      tags: 'felx, table, padding, margin',
      description: '多种方式实现等宽均分布局',
      category: 'layout',
    },
    {
      title: '布局-居中',
      path: 'LayoutCenter',
      icon: '',
      tags: 'felx, inline-block, absolute',
      description: '水平居中，垂直居中',
      category: 'layout',
    },
    {
      title: '布局-双飞翼',
      path: 'LayoutDoubleFly',
      icon: '',
      tags: 'float, margin, padding',
      description:
        '双飞翼布局，左中右三列，中间列部分溢出隐藏，左右给padding, 左侧与右侧的元素分别给负值margin',
      category: 'layout',
    },
    {
      title: '布局-圣杯布局',
      path: 'LayoutHoly',
      icon: '',
      tags: 'float, margin',
      description:
        '三列布局，居中部分100%宽度，左右两边float浮动，并给margin负值',
      category: 'layout',
    },
    {
      title: '布局-flex',
      path: 'LayoutFlex',
      icon: '',
      tags: 'flex-direction, justify-content, align-items',
      description: 'Flex弹性伸缩布局，flex的每个特性示例展示效果',
      category: 'layout',
    },
    {
      title: '布局-定宽全屏布局',
      path: 'LayoutFullFixWidth',
      icon: '',
      tags: 'flex-direction, justify-content, align-items',
      description: '定宽布局全屏布局',
      category: 'layout',
    },
    {
      title: '布局-全屏布局',
      path: 'LayoutFullFlex',
      icon: '',
      tags: 'absolute, percent',
      description: '全屏布局',
      category: 'layout',
    },
    {
      title: '布局-自适应全屏布局',
      path: 'LayoutFlexAuto',
      icon: '',
      tags: 'absolute, percent',
      description: '外层元素不定宽自适应全屏布局',
      category: 'layout',
    },
    {
      title: '布局-自适应全屏布局',
      path: 'LayoutFullFlexPrecent',
      icon: '',
      tags: 'absolute, percent',
      description: '外层元素不定宽自适应全屏布局',
      category: 'layout',
    },
    {
      title: '布局-百分比全屏布局',
      path: 'LayoutFullPrecent',
      icon: '',
      tags: 'absolute, percent',
      description: '百分比给定元素宽度，全屏布局',
      category: 'layout',
    },
  ],
}
